# Generated by Django 2.2.2 on 2019-07-02 10:40

import authentication.validations
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('authentication', '0002_auto_20190627_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='locations.City'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(validators=[authentication.validations.validate_birthday]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, error_messages={'unique': 'A user with that username already exists'}, max_length=50, unique=True, validators=[authentication.validations.UsernameValidator()]),
        ),
    ]
