# Generated by Django 2.2.2 on 2019-07-09 07:34

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20190702_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=authentication.models.get_user_photo_path),
        ),
    ]
