# Generated by Django 2.2.2 on 2019-07-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0002_auto_20190716_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='friendships',
        ),
        migrations.AddField(
            model_name='friendship',
            name='friends',
            field=models.ManyToManyField(related_name='_friendship_friends_+', to='friendship.Friendship'),
        ),
    ]
