# Generated by Django 2.2.2 on 2019-07-02 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='country',
        ),
    ]
