# Generated by Django 2.2.2 on 2019-07-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_office_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='photo',
            field=models.ImageField(blank=True, upload_to='offices_photos'),
        ),
    ]
